### PR TITLE
Replace transport by a new winston 3.x complient one.

### PR DESCRIPTION
**Pull request by cutesquirrel**
ES6 style (+ babel and ./dist/ directory containing the compiled version. package.json/main points to ./dist/winston-logstash.js).
Reviewed the tests: I still have an error on the end, unable to figure out why for the moment. But the tests are OK.

### CODE REVIEW

**Comment by dmichelin** [comment]
I tested this with my machine and it also appears to be working as expected.

**Comment by djMax** [comment]
Have you had a chance to look at the tests failing?

**Comment by yagodorea** [comment]
Will this ever be merged?

**Comment by AchiniP** [comment]
Still there is no compatibele winston logstash version for winston 3.x ?

**Comment by jaakkos** [comment]
I finally managed to find time to add Winston 3.x support while keeping the 2.x support.

**Pull request closed without merging**
